name: CI
on:
  push:
    branches: ["main", "devel"]
    paths:
      - '**.go'
      - '**.yml'
  pull_request:
    branches: ["main"]

jobs:
  test:
    strategy:
      matrix:
        go-version: ['stable', 'oldstable', '1.20']
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v4
      - name: test
        env:
          GOTOOLCHAIN: local
        run: go test -v ./...
